### ISSUE TITLE
Visual layout for BannerEditor

### ISSUE THREAD

**Issue by dfosco** [vtex-apps/storefront-banner#2]
- [x] Empty State on editor
 - [x] Current image on editor (_Breno_)
 - [x] Image preview on editor (_Breno_)
 - [x] Bottom bar
 - [x] Alt-text field
 - [x] Style fields properly
 - [x] Create styles to toggle fields with “Add new image”

**Comment by dfosco** [comment]
@brenoc The layout is done here, but we still need quite a bit of interaction to have this issue all well and done:

 - Have the current image in the banner appear where the placeholder image is now
 - Live-preview of the new image when you paste in a new URL (we have to think about cropping here, even if it's a stop-gap solution)
 - Hide the _Adicionar nova imagem_ button when there is already an image configured — the user would just edit the current information in the fields. The default for `data-is-adding` becomes `true`
 - Disable the _Salvar_ button while there are no changes in any field yet

**Comment by brenoc** [comment]
@dfosco what do you think of the title of the Component appear at the StatusBar like:

![title](https://cloud.githubusercontent.com/assets/284515/9073651/27458590-3ad9-11e5-94ef-56a84f694244.png)

**Comment by dfosco** [comment]
YASSSS.

I thought about that before but forgot to open an issue about it. Cool, do
it!

danielfos.co
+55 21 97957-1497

**Comment by brenoc** [comment]
Image preview is done!

**Comment by amoreira** [comment]
:+1:

**Comment by brenoc** [comment]
Done! **To see this update you need to update storefront-editor as well.**

![title](https://cloud.githubusercontent.com/assets/284515/9099496/8557ddbc-3ba7-11e5-9462-f1ec9818f56c.png)
