### ISSUE TITLE
Component title on ComponentEditMode

### ISSUE THREAD

**Issue by dfosco** [vtex-apps/storefront-banner#4]
@brenoc 

Just added a title to the banner component when on Edit Mode (`BannerEditMode.jsx`) — seems to me like a better way to make users understand what they are about to click. We will flesh out the interface details during testing.

It's hard-coded though, so we need to pull the correct value with the component name from Flux.

**Comment by dfosco** [comment]
@brenoc Here's what I mean... *Banner* on the top of the highlighted area

<img width="322" alt="screen shot 2015-08-04 at 4 43 10 pm" src="https://cloud.githubusercontent.com/assets/3229933/9070779/efb7f330-3ac7-11e5-89e0-e42d1c80c1a4.png">

**Comment by brenoc** [comment]
This is shown when the Edit mode is active, right? The red border and the red title will be a Storefront default or that's up to the component author?

**Comment by dfosco** [comment]
Haha, I just talked about this [here](https://github.com/vtex-apps/storefront-banner/issues/1) :smile:

**Comment by dfosco** [comment]
This issue is _so_ closed.
